/**
 * Editor theme built from the app's CSS tokens + a LaTeX-tuned syntax palette
 * (light & dark). Syntax colours are CSS variables defined on `.cm-editor` so
 * the highlight style is shared between both themes.
 */
import { EditorView } from '@codemirror/view';
import { HighlightStyle } from '@codemirror/language';
import { tags as t } from '@lezer/highlight';
import type { Extension } from '@codemirror/state';
import { latexTags } from './language';

const lightVars = {
  '--cm-cmd': '#5546d6',
  '--cm-env': '#0e7490',
  '--cm-heading': '#4338ca',
  '--cm-title': '#18181b',
  '--cm-math': '#b45309',
  '--cm-math-cmd': '#c2410c',
  '--cm-math-bg': 'rgb(245 158 11 / 0.075)',
  '--cm-math-border': 'rgb(245 158 11 / 0.35)',
  '--cm-label': '#15803d',
  '--cm-cite': '#be185d',
  '--cm-path': '#0369a1',
  '--cm-opt': '#71717a',
  '--cm-op': '#9333ea',
  '--cm-comment': '#8b8b96',
  '--cm-bracket': '#8a8a94',
  '--cm-meta': '#52525b',
  '--cm-string': '#0f766e',
  '--cm-number': '#0369a1',
  '--cm-prop': '#7c3aed',
  '--cm-search': 'rgb(250 204 21 / 0.35)',
  '--cm-search-active': 'rgb(249 115 22 / 0.45)',
  '--cm-selection': 'color-mix(in srgb, var(--tx-accent) 18%, transparent)',
  '--cm-selection-focus': 'color-mix(in srgb, var(--tx-accent) 24%, transparent)',
  '--cm-active-line': 'color-mix(in srgb, var(--tx-accent) 4.5%, transparent)',
};

const darkVars: typeof lightVars = {
  '--cm-cmd': '#a8a4ff',
  '--cm-env': '#5fd0de',
  '--cm-heading': '#b9b5ff',
  '--cm-title': '#f4f4f5',
  '--cm-math': '#f2b45c',
  '--cm-math-cmd': '#fb9a5b',
  '--cm-math-bg': 'rgb(245 165 36 / 0.065)',
  '--cm-math-border': 'rgb(245 165 36 / 0.35)',
  '--cm-label': '#6ee7a0',
  '--cm-cite': '#f9a8d4',
  '--cm-path': '#7cc4fa',
  '--cm-opt': '#8b8b96',
  '--cm-op': '#c49bff',
  '--cm-comment': '#6e6e7a',
  '--cm-bracket': '#8b8b96',
  '--cm-meta': '#a1a1aa',
  '--cm-string': '#5eead4',
  '--cm-number': '#7cc4fa',
  '--cm-prop': '#c4b5fd',
  '--cm-search': 'rgb(250 204 21 / 0.22)',
  '--cm-search-active': 'rgb(249 115 22 / 0.42)',
  '--cm-selection': 'color-mix(in srgb, var(--tx-accent) 24%, transparent)',
  '--cm-selection-focus': 'color-mix(in srgb, var(--tx-accent) 32%, transparent)',
  '--cm-active-line': 'rgb(255 255 255 / 0.028)',
};

const base = EditorView.theme({
  '&': {
    height: '100%',
    backgroundColor: 'var(--tx-surface)',
    color: 'var(--tx-fg)',
  },
  '&.cm-focused': { outline: 'none' },
  '.cm-scroller': { overflow: 'auto', fontVariantLigatures: 'none' },
  '.cm-content': { padding: '10px 0 0', caretColor: 'var(--tx-accent)' },
  '.cm-line': { padding: '0 20px 0 14px' },
  '.cm-cursor, .cm-dropCursor': { borderLeft: '2px solid var(--tx-accent)', marginLeft: '-1px' },
  '&.cm-focused > .cm-scroller > .cm-selectionLayer .cm-selectionBackground': { background: 'var(--cm-selection-focus)' },
  '.cm-selectionBackground': { background: 'var(--cm-selection)' },
  '.cm-content ::selection': { background: 'transparent' },
  '.cm-activeLine': { backgroundColor: 'var(--cm-active-line)' },
  '.cm-gutters': {
    backgroundColor: 'var(--tx-surface)',
    color: 'var(--tx-fg-subtle)',
    border: 'none',
    paddingLeft: '6px',
  },
  '.cm-lineNumbers .cm-gutterElement': {
    padding: '0 6px 0 10px',
    minWidth: '34px',
    fontSize: '0.86em',
    opacity: '0.75',
    fontVariantNumeric: 'tabular-nums',
  },
  '.cm-activeLineGutter': { backgroundColor: 'transparent', color: 'var(--tx-fg)' },
  '.cm-activeLineGutter.cm-gutterElement': { opacity: '1' },
  '.cm-foldGutter .cm-gutterElement': {
    color: 'var(--tx-fg-subtle)',
    opacity: '0',
    transition: 'opacity 120ms',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '14px',
  },
  '.cm-gutters:hover .cm-foldGutter .cm-gutterElement, .cm-foldGutter .cm-gutterElement .cm-fold-closed': { opacity: '1' },
  '.cm-fold-marker': { display: 'inline-flex', cursor: 'pointer', borderRadius: '4px' },
  '.cm-fold-marker:hover': { color: 'var(--tx-fg)', background: 'var(--tx-hover)' },
  '.cm-foldPlaceholder': {
    background: 'var(--tx-accent-soft)',
    color: 'var(--tx-accent)',
    border: 'none',
    borderRadius: '5px',
    padding: '0 6px',
    margin: '0 3px',
    fontSize: '0.85em',
    fontFamily: 'var(--font-sans)',
  },
  '.cm-matchingBracket, &.cm-focused .cm-matchingBracket': {
    backgroundColor: 'var(--tx-accent-soft)',
    outline: '1px solid color-mix(in srgb, var(--tx-accent) 45%, transparent)',
    borderRadius: '2px',
    color: 'inherit',
  },
  '.cm-nonmatchingBracket, &.cm-focused .cm-nonmatchingBracket': { backgroundColor: 'var(--tx-danger-soft)', color: 'var(--tx-danger)' },
  '.cm-searchMatch': { backgroundColor: 'var(--cm-search)', borderRadius: '2px' },
  '.cm-searchMatch.cm-searchMatch-selected': { backgroundColor: 'var(--cm-search-active)' },
  '.cm-selectionMatch': { backgroundColor: 'color-mix(in srgb, var(--tx-accent) 10%, transparent)', borderRadius: '2px' },
  '.cm-placeholder': { color: 'var(--tx-fg-subtle)', fontStyle: 'italic' },
  '.cm-specialChar': { color: 'var(--tx-danger)' },

  // Panels (search, vim status…)
  '.cm-panels': { backgroundColor: 'var(--tx-surface)', color: 'var(--tx-fg)', zIndex: '5' },
  '.cm-panels.cm-panels-top': { borderBottom: '1px solid var(--tx-border)' },
  '.cm-panels.cm-panels-bottom': { borderTop: '1px solid var(--tx-border)' },
  '.cm-vim-panel': { padding: '2px 12px', fontFamily: 'var(--font-mono)', fontSize: '12px', minHeight: '22px' },
  '.cm-vim-panel input': { background: 'transparent', color: 'var(--tx-fg)', outline: 'none', border: 'none', fontFamily: 'inherit' },
  '.cm-fat-cursor': { background: 'color-mix(in srgb, var(--tx-accent) 70%, transparent) !important', color: 'var(--tx-accent-fg) !important' },
  '&:not(.cm-focused) .cm-fat-cursor': { background: 'none !important', outline: '1px solid var(--tx-accent) !important', color: 'inherit !important' },

  // Tooltips
  '.cm-tooltip': {
    backgroundColor: 'var(--tx-elevated)',
    color: 'var(--tx-fg)',
    border: '1px solid var(--tx-border)',
    borderRadius: '10px',
    boxShadow: '0 12px 32px -8px rgb(0 0 0 / 0.22), 0 2px 6px -2px rgb(0 0 0 / 0.1)',
    fontFamily: 'var(--font-sans)',
    fontSize: '12.5px',
    overflow: 'hidden',
  },
  '.cm-tooltip.cm-tooltip-hover, .cm-tooltip.cm-tx-tooltip': { maxWidth: '520px' },
  '.cm-tooltip-arrow:before': { borderTopColor: 'var(--tx-border) !important', borderBottomColor: 'var(--tx-border) !important' },
  '.cm-tooltip-arrow:after': { borderTopColor: 'var(--tx-elevated) !important', borderBottomColor: 'var(--tx-elevated) !important' },

  // Autocomplete
  '.cm-tooltip.cm-tooltip-autocomplete': { padding: '4px' },
  '.cm-tooltip.cm-tooltip-autocomplete > ul': {
    fontFamily: 'var(--font-sans)',
    maxHeight: '18.5em',
    minWidth: '260px',
    maxWidth: '520px',
  },
  '.cm-tooltip.cm-tooltip-autocomplete > ul > li': {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '3px 8px 3px 4px',
    borderRadius: '6px',
    lineHeight: '20px',
    color: 'var(--tx-fg)',
  },
  '.cm-tooltip.cm-tooltip-autocomplete > ul > li[aria-selected]': {
    background: 'var(--tx-accent)',
    color: 'var(--tx-accent-fg)',
  },
  '.cm-tooltip.cm-tooltip-autocomplete > ul > li[aria-selected] .cm-completionDetail, .cm-tooltip.cm-tooltip-autocomplete > ul > li[aria-selected] .cm-completionMatchedText': {
    color: 'inherit',
    opacity: '0.85',
  },
  '.cm-completionLabel': { fontFamily: 'var(--font-mono)', fontSize: '12.5px', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  '.cm-completionMatchedText': { textDecoration: 'none', fontWeight: '700', color: 'var(--tx-accent)' },
  '.cm-completionDetail': {
    marginLeft: 'auto',
    paddingLeft: '12px',
    fontStyle: 'normal',
    fontSize: '11px',
    color: 'var(--tx-fg-subtle)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: '220px',
  },
  '.cm-completionIcon': {
    width: '20px',
    height: '20px',
    padding: '0',
    marginRight: '0',
    flexShrink: '0',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '5px',
    fontSize: '11px',
    fontFamily: 'var(--font-mono)',
    fontWeight: '600',
    opacity: '1',
    background: 'var(--tx-surface-2)',
    color: 'var(--tx-fg-muted)',
    boxShadow: 'inset 0 0 0 1px var(--tx-border)',
  },
  'li[aria-selected] .cm-completionIcon': { background: 'rgb(255 255 255 / 0.18)', color: 'inherit', boxShadow: 'none' },
  '.cm-completionIcon-cmd:after': { content: '"\\\\"', color: 'var(--cm-cmd)' },
  '.cm-completionIcon-env:after': { content: '"{}"', color: 'var(--cm-env)' },
  '.cm-completionIcon-math:after': { content: '"∑"', color: 'var(--cm-math)' },
  '.cm-completionIcon-macro:after': { content: '"λ"', color: 'var(--cm-op)' },
  '.cm-completionIcon-label:after': { content: '"#"', color: 'var(--cm-label)' },
  '.cm-completionIcon-cite:after': { content: '"“"', color: 'var(--cm-cite)' },
  '.cm-completionIcon-file:after': { content: '"⌸"', color: 'var(--cm-path)' },
  '.cm-completionIcon-package:after': { content: '"◆"', color: 'var(--cm-path)' },
  '.cm-completionIcon-snippet:after': { content: '"⌁"', color: 'var(--tx-accent)' },
  '.cm-completionIcon-keyword:after, .cm-completionIcon-text:after, .cm-completionIcon-variable:after': { content: '"·"' },
  'li[aria-selected] .cm-completionIcon:after': { color: 'inherit !important' },
  '.cm-tooltip.cm-completionInfo': {
    padding: '10px 12px',
    maxWidth: '360px',
    lineHeight: '1.5',
    marginLeft: '4px',
    marginTop: '-4px',
  },

  // Lint
  '.cm-lintRange': { backgroundImage: 'none', paddingBottom: '0' },
  '.cm-lintRange-error': { textDecoration: 'underline wavy var(--tx-danger)', textDecorationThickness: '1px', textUnderlineOffset: '3px', textDecorationSkipInk: 'none' },
  '.cm-lintRange-warning': { textDecoration: 'underline wavy var(--tx-warning)', textDecorationThickness: '1px', textUnderlineOffset: '3px', textDecorationSkipInk: 'none' },
  '.cm-lintRange-info': { textDecoration: 'underline dotted var(--tx-info)', textUnderlineOffset: '3px' },
  '.cm-lintRange-info.cm-badbox': { textDecoration: 'underline dotted color-mix(in srgb, var(--tx-fg-subtle) 70%, transparent)' },
  '.cm-lintRange-active': { backgroundColor: 'var(--tx-hover)' },
  '.cm-gutter-lint': { width: '12px' },
  '.cm-gutter-lint .cm-gutterElement': { padding: '0', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  '.cm-lint-marker': { width: '7px', height: '7px', borderRadius: '99px', content: 'none' },
  '.cm-lint-marker-error': { content: 'none', background: 'var(--tx-danger)', boxShadow: '0 0 0 2px var(--tx-danger-soft)' },
  '.cm-lint-marker-warning': { content: 'none', background: 'var(--tx-warning)', boxShadow: '0 0 0 2px var(--tx-warning-soft)' },
  '.cm-lint-marker-info': { content: 'none', background: 'var(--tx-info)', opacity: '0.6' },
  '.cm-tooltip-lint': { padding: '4px' },
  '.cm-diagnostic': {
    padding: '6px 10px 6px 12px',
    borderLeft: '3px solid var(--tx-info)',
    borderRadius: '6px',
    fontFamily: 'var(--font-sans)',
    marginLeft: '0',
    whiteSpace: 'pre-wrap',
    maxWidth: '480px',
  },
  '.cm-diagnostic + .cm-diagnostic': { marginTop: '4px' },
  '.cm-diagnostic-error': { borderLeftColor: 'var(--tx-danger)', background: 'var(--tx-danger-soft)' },
  '.cm-diagnostic-warning': { borderLeftColor: 'var(--tx-warning)', background: 'var(--tx-warning-soft)' },
  '.cm-diagnostic-info': { borderLeftColor: 'var(--tx-info)', background: 'var(--tx-info-soft)' },
  '.cm-diagnosticSource': { fontSize: '10.5px', opacity: '0.65', marginTop: '2px', textTransform: 'uppercase', letterSpacing: '0.04em' },
  '.cm-diagnosticAction': {
    background: 'var(--tx-accent)',
    color: 'var(--tx-accent-fg)',
    borderRadius: '5px',
    padding: '1px 8px',
    font: 'inherit',
    fontSize: '11.5px',
  },
  '.cm-panel.cm-panel-lint': { display: 'none' },

  // Math regions
  '.cm-math-inline': { backgroundColor: 'var(--cm-math-bg)', borderRadius: '3px', boxShadow: '0 0 0 1px var(--cm-math-bg)' },
  '.cm-math-block': { backgroundColor: 'var(--cm-math-bg)', boxShadow: 'inset 2px 0 0 var(--cm-math-border)' },

  // Flash after reveal
  '.cm-flash-line': { animation: 'cm-flash 1.4s ease-out' },
  '@keyframes cm-flash': {
    '0%': { backgroundColor: 'color-mix(in srgb, var(--tx-accent) 26%, transparent)' },
    '100%': { backgroundColor: 'transparent' },
  },

  // Rich text mode
  '.cm-rich-h0': { fontSize: '1.42em', fontWeight: '700', lineHeight: '1.6' },
  '.cm-rich-h1': { fontSize: '1.32em', fontWeight: '700', lineHeight: '1.6' },
  '.cm-rich-h2': { fontSize: '1.2em', fontWeight: '650', lineHeight: '1.6' },
  '.cm-rich-h3': { fontSize: '1.1em', fontWeight: '650' },
  '.cm-rich-h4': { fontSize: '1.04em', fontWeight: '600' },
  '.cm-rich-h5, .cm-rich-h6': { fontWeight: '600' },
  '.cm-rich-dim': { opacity: '0.5' },
  '.cm-rich-bold': { fontWeight: '700' },
  '.cm-rich-italic': { fontStyle: 'italic' },
  '.cm-rich-underline': { textDecoration: 'underline', textUnderlineOffset: '3px' },
  '.cm-rich-strike': { textDecoration: 'line-through' },
  '.cm-rich-sc': { fontVariant: 'small-caps' },
  '.cm-rich-mono': { backgroundColor: 'var(--tx-surface-2)', borderRadius: '3px' },
  '.cm-rich-item': { color: 'var(--tx-accent)', fontWeight: '700' },
  '.cm-rich-link': { textDecoration: 'underline', textDecorationColor: 'color-mix(in srgb, var(--cm-path) 50%, transparent)', textUnderlineOffset: '3px' },
  '.cm-rich-title': { fontSize: '1.15em', fontWeight: '700' },

  // Remote collaborator cursors (y-codemirror.next)
  '.cm-ySelectionInfo': {
    fontFamily: 'var(--font-sans)',
    fontSize: '10.5px',
    fontWeight: '600',
    padding: '1px 5px',
    borderRadius: '4px 4px 4px 0',
    top: '-1.35em',
    opacity: '1',
    transitionDelay: '1.5s',
  },
});

export function editorTheme(dark: boolean): Extension {
  return [EditorView.theme({ '&': dark ? darkVars : lightVars }, { dark }), base];
}

export function fontTheme(opts: { fontFamily: string; fontSize: number; lineHeight: number }): Extension {
  return EditorView.theme({
    '&': { fontSize: `${opts.fontSize}px` },
    '.cm-scroller': { fontFamily: opts.fontFamily, lineHeight: String(opts.lineHeight) },
    '.cm-tooltip.cm-completionInfo, .cm-tooltip-autocomplete': { fontSize: '12.5px' },
  });
}

export const highlightStyle = HighlightStyle.define([
  { tag: t.comment, color: 'var(--cm-comment)', fontStyle: 'italic' },
  { tag: [t.keyword, t.definitionKeyword], color: 'var(--cm-cmd)' },
  { tag: t.heading, color: 'var(--cm-heading)', fontWeight: '700' },
  { tag: latexTags.envKeyword, color: 'var(--cm-env)' },
  { tag: t.className, color: 'var(--cm-env)', fontWeight: '500' },
  { tag: [t.meta, t.monospace], color: 'var(--cm-meta)' },
  { tag: t.string, color: 'var(--cm-string)' },
  { tag: t.number, color: 'var(--cm-number)' },
  { tag: [t.propertyName, t.attributeName], color: 'var(--cm-prop)' },
  { tag: t.labelName, color: 'var(--cm-label)' },
  { tag: t.typeName, color: 'var(--cm-env)' },
  { tag: t.function(t.variableName), color: 'var(--cm-cmd)' },
  { tag: t.strong, fontWeight: '700' },
  { tag: t.emphasis, fontStyle: 'italic' },
  { tag: t.strikethrough, textDecoration: 'line-through' },
  { tag: t.link, color: 'var(--cm-path)', textDecoration: 'underline' },
  { tag: t.url, color: 'var(--cm-path)' },
  { tag: t.invalid, color: 'var(--tx-danger)' },
  { tag: t.heading1, fontSize: '1.3em' },
  { tag: t.heading2, fontSize: '1.15em' },
  { tag: t.quote, color: 'var(--cm-meta)', fontStyle: 'italic' },
  { tag: t.processingInstruction, color: 'var(--cm-opt)' },
  { tag: [t.operator, t.special(t.string)], color: 'var(--cm-op)' },
  // Math wins over the generic token colours above.
  { tag: latexTags.math, color: 'var(--cm-math)' },
  { tag: latexTags.mathCmd, color: 'var(--cm-math-cmd)' },
  { tag: latexTags.mathDelim, color: 'var(--cm-math)', fontWeight: '600' },
  // LaTeX argument kinds (inherited by the argument's children)
  { tag: latexTags.sectionTitle, color: 'var(--cm-title)', fontWeight: '650' },
  { tag: latexTags.optional, color: 'var(--cm-opt)' },
  { tag: latexTags.path, color: 'var(--cm-path)' },
  { tag: latexTags.label, color: 'var(--cm-label)' },
  { tag: latexTags.cite, color: 'var(--cm-cite)' },
  { tag: [t.bracket, t.paren, t.squareBracket, t.brace], color: 'var(--cm-bracket)' },
]);
